### ISSUE TITLE
The migration is failed when the database is postgresql

### ISSUE THREAD

**Issue by mrab72** [logspace-ai/langflow#1021]
**Describe the bug**
I encountered an issue while running latest Langflow with PostgreSQL as the database. It seems to be related to a migration conflict between the latest database structure and the previous one. Below is the error message I received:

```
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 578, in run_env

    util.load_python_file(self.dir, "env.py")

  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file

    module = load_module_py(module_id, path)

  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py

    spec.loader.exec_module(module)  # type: ignore

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/usr/local/lib/python3.10/site-packages/langflow/alembic/env.py", line 81, in <module>

    run_migrations_online()

  File "/usr/local/lib/python3.10/site-packages/langflow/alembic/env.py", line 75, in run_migrations_online

    context.run_migrations()

  File "<string>", line 8, in run_migrations

  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 937, in run_migrations

    self.get_context().run_migrations(**kw)

  File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrations

    step.migration_fn(**kw)

  File "/usr/local/lib/python3.10/site-packages/langflow/alembic/versions/260dbcc8b680_adds_tables.py", line 34, in upgrade

    index["name"] for index in inspector.get_indexes("flowstyle")

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 605, in get_indexes

    return self.dialect.get_indexes(

  File "<string>", line 2, in get_indexes

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache

    ret = fn(self, con, *args, **kw)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 4246, in get_indexes

    table_oid = self.get_table_oid(

  File "<string>", line 2, in get_table_oid

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache

    ret = fn(self, con, *args, **kw)

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3668, in get_table_oid

    raise exc.NoSuchTableError(table_name)

sqlalchemy.exc.NoSuchTableError: flowstyle

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan

    async with self.lifespan_context(app) as maybe_state:

  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__

    await self._router.startup()
```

I just update the langflow version to the `0.5.2` and then run the `langflow run` command.
### Instructions to generate the error:
```
docker run --name my-postgres-container -e POSTGRES_PASSWORD=mysecret -p 5432:5432 -d postgres
pip install langflow==0.5.2
export LANGFLOW_DATABASE_URL=postgresql://postgres:mysecret@0.0.0.0:5432/postgres 
langflow run
```

**Comment by ogabrielluiz** [comment]
#1034 Fixes this. Could you report back so we can close this?
