### ISSUE TITLE
cannot import name 'DEFAULT_CONNECTION_STRING' in  v0.6.3a5

### ISSUE THREAD

**Issue by josephykwang** [logspace-ai/langflow#1239]
```
% git branch
* (HEAD detached at v0.6.3a5)
  dev
% cd docker_example 
% docker compose up

[+] Running 1/0
 ✔ Container docker_example-langflow-1  Created                                                                    0.0s 
Attaching to langflow-1
langflow-1  | Traceback (most recent call last):
langflow-1  |   File "/home/user/.local/bin/langflow", line 5, in <module>
langflow-1  |     from langflow.__main__ import main
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/__init__.py", line 5, in <module>
langflow-1  |     from langflow.processing.process import load_flow_from_json
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/processing/process.py", line 10, in <module>
langflow-1  |     from langflow.graph import Graph
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/graph/__init__.py", line 2, in <module>
langflow-1  |     from langflow.graph.graph.base import Graph
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 7, in <module>
langflow-1  |     from langflow.graph.graph.constants import lazy_load_vertex_dict
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/graph/graph/constants.py", line 1, in <module>
langflow-1  |     from langflow.graph.vertex import types
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/graph/vertex/types.py", line 5, in <module>
langflow-1  |     from langflow.graph.vertex.base import Vertex
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 9, in <module>
langflow-1  |     from langflow.interface.initialize import loading
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 17, in <module>
langflow-1  |     from langflow.interface.custom_lists import CUSTOM_NODES
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/interface/custom_lists.py", line 7, in <module>
langflow-1  |     from langflow.interface.agents.custom import CUSTOM_AGENTS
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/interface/agents/__init__.py", line 1, in <module>
langflow-1  |     from langflow.interface.agents.base import AgentCreator
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/interface/agents/base.py", line 5, in <module>
langflow-1  |     from langflow.custom.customs import get_custom_nodes
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/custom/customs.py", line 1, in <module>
langflow-1  |     from langflow.template import frontend_node
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/template/frontend_node/__init__.py", line 1, in <module>
langflow-1  |     from langflow.template.frontend_node import (
langflow-1  |   File "/home/user/.local/lib/python3.10/site-packages/langflow/template/frontend_node/memories.py", line 7, in <module>
langflow-1  |     from langchain.memory.chat_message_histories.postgres import DEFAULT_CONNECTION_STRING
langflow-1  | ImportError: cannot import name 'DEFAULT_CONNECTION_STRING' from 'langchain.memory.chat_message_histories.postgres' (/home/user/.local/lib/python3.10/site-packages/langchain/memory/chat_message_histories/postgres.py)
langflow-1 exited with code 1
```

**Comment by ogabrielluiz** [comment]
@dosu-bot  The reason this is happening is because version 0.0.351 of langchain has migrated to langchain_community on certain integrations. 

In the 0.6.3 version of Langflow we have fixed it.
