### ISSUE TITLE
Upgrading 0.5.12 to 0.6.4 failed, and directly using 0.6.4 to start the program also failed.

### ISSUE THREAD

**Issue by lsg328** [logspace-ai/langflow#1274]
**Describe the bug**
When starting Langflow with PostgreSQL, an error occurs when upgrading from 0.5.12 to 0.6.4. Even when attempting to start directly with version 0.6.4 and a new database, errors persist, specifically between versions 0.6.0 - 0.6.4. 

**Version**
 - Version 0.6.0 - 0.6.4.

**Log**
upgrading from 0.5.12 to 0.6.4
```
[2024-01-02 11:58:28 +0800] [10953] [ERROR] Traceback (most recent call last):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/service.py", line 149, in run_migrations
    command.check(alembic_cfg)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/command.py", line 290, in check
    script_directory.run_env()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/alembic/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/command.py", line 279, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 570, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 591, in _run_environment
    raise util.CommandError("Target database is not up to date.")
alembic.util.exc.CommandError: Target database is not up to date.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/starlette/routing.py", line 705, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/main.py", line 19, in lifespan
    initialize_services()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/utils.py", line 206, in initialize_services
    raise exc
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/utils.py", line 203, in initialize_services
    initialize_database(fix_migration=fix_migration)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/utils.py", line 52, in initialize_database
    raise exc
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/utils.py", line 32, in initialize_database
    database_service.run_migrations(fix=fix_migration)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/service.py", line 152, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/alembic/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/alembic/versions/7d2162acc8b2_adds_updated_at_and_folder_cols.py", line 32, in upgrade
    with op.batch_alter_table('apikey', schema=None) as batch_op:
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/operations/base.py", line 398, in batch_alter_table
    impl.flush()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/operations/batch.py", line 116, in flush
    fn(*arg, **kw)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/ddl/postgresql.py", line 187, in alter_column
    super().alter_column(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/ddl/impl.py", line 241, in alter_column
    self._exec(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
    ret = self._execute_context(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block
```
start directly with version 0.6.4 and a new database
```
                             RuntimeError: Something went wrong running
                             migrations. Please, run `langflow migration --fix`
[2024-01-02 12:11:46 +0800] [11793] [ERROR] Traceback (most recent call last):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/service.py", line 156, in run_migrations
    command.check(alembic_cfg)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/alembic/command.py", line 300, in check
    raise util.AutogenerateDiffsDetected(
alembic.util.exc.AutogenerateDiffsDetected: New upgrade operations detected: [('add_constraint', UniqueConstraint(Column('id', NullType(), table=<apikey>))), ('add_constraint', UniqueConstraint(Column('id', NullType(), table=<flow>))), ('add_constraint', UniqueConstraint(Column('id', NullType(), table=<user>)))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/starlette/routing.py", line 705, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/main.py", line 19, in lifespan
    initialize_services()
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/utils.py", line 206, in initialize_services
    raise exc
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/utils.py", line 203, in initialize_services
    initialize_database(fix_migration=fix_migration)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/utils.py", line 52, in initialize_database
    raise exc
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/utils.py", line 32, in initialize_database
    database_service.run_migrations(fix=fix_migration)
  File "/usr/lib/anaconda3/envs/langflow-0.6.4/lib/python3.10/site-packages/langflow/services/database/service.py", line 160, in run_migrations
    raise RuntimeError(
RuntimeError: Something went wrong running migrations. Please, run `langflow migration --fix
```

[SQL: ALTER TABLE apikey ALTER COLUMN name SET NOT NULL]
(Background on this error at: https://sqlalche.me/e/20/2j85)

**Screenshots**
upgrading from 0.5.12 to 0.6.4
![image](https://github.com/logspace-ai/langflow/assets/24787621/2f8b6a8b-7f39-402b-bf35-4c57e2db0ce6)

 start directly with version 0.6.4 and a new database
![image](https://github.com/logspace-ai/langflow/assets/24787621/cf0e4148-2dfc-49f2-a24d-7c566e0e1a91)

**Comment by lsg328** [comment]
Manually executing the SQL statement "ALTER TABLE apikey ALTER COLUMN name SET NOT NULL" can be executed normally. And if you use the new database directly (no tables exist), you will also get an error.

**Comment by lsg328** [comment]
@ogabrielluiz Versions after langflow0.5.12 will have this problem when using postgreSQL, whether it is an upgrade or a new environment

**Comment by lsg328** [comment]
Problems still exist with the latest version

**Comment by ogabrielluiz** [comment]
@lsg328 Could you test version 0.6.9 if it is working on your end?
