### ISSUE TITLE
 ERROR    - base - 'Python' is not a valid Language 

### ISSUE THREAD

**Issue by sandyis** [logspace-ai/langflow#1290]
i have python three installed and GUI is working and model is created but when i try to build it using ⚡ , i see below erros which ends in after long trace in `ValueError: Error building node Chroma(ID:Chroma-19VNr): If documents are provided, there must be at least one document.  ERROR    2024-01-03 21:04:50 - ERROR    - chat - Error while building the flow: %s `
full log attached

`    2024-01-03 21:04:48 - ERROR    - base - 'Python' is not a valid Language                                                                                      base.py:329`
                             Traceback (most recent call last):

                               File "/home/test/.local/bin/langflow", line 8, in <module>
                                 sys.exit(main())
                                 |   |    -> <function main at 0x7f99d76a1e10>
                                 |   -> <built-in function exit>
                                 -> <module 'sys' (built-in)>
                               File "/home/test/.local/lib/python3.10/site-packages/langflow/__main__.py", line 380, in main
**_............see attached for fulltrace `_**

- langflow 0.6.4
- python3 --version
- Python 3.10.12
-  which python3
- /usr/bin/python3
 - Browser chrome Version 120.0.6099.130 (Official Build) (64-bit)
![image](https://github.com/logspace-ai/langflow/assets/24884891/1c4211bd-62cd-48a5-a4e9-a0e023a97b76)

**Comment by sandyis** [comment]
yes figured it out also i had my "pdf dir" reader inputting to a "txt sppliter" ...
thanks for reply
