### ISSUE TITLE
The Make backend command spits out error.

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#1325]
When you run Make backend in a virtual environment of Python 3.9 in Miniconda, it does not run with the following error.

(langflow v0.6.4) 

Also, in the case of Dev Brunch, the dependency declaration should be changed to support Langchain's latest version, 0.1.0.

like

langchain = ">=0.1.0, <0.2.0"

I also changed the lock file like this. The dependencies between the “LangChain Community” package and the “LangChain Core” package seem to be twisted and twisted.

```
 ~/work/langflow  ◈ v0.6.4 ±  make backend          
make install_backend
make[1]: Entering directory '/home/battlecruser/work/langflow'
poetry install --extras deploy
Installing dependencies from lock file

Package operations: 11 installs, 0 updates, 0 removals

  • Installing vine (5.1.0)
  • Installing amqp (5.2.0)
  • Installing billiard (4.2.0)
  • Installing click-didyoumean (0.3.0)
  • Installing click-plugins (1.1.1)
  • Installing click-repl (0.3.0)
  • Installing kombu (5.3.4)
  • Installing celery (5.3.6)
  • Installing humanize (4.9.0)
  • Installing redis (4.6.0)
  • Installing flower (2.0.1)

Installing the current project: langflow (0.6.4)
make[1]: Leaving directory '/home/battlecruser/work/langflow'
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
make: [Makefile:72: backend] Error 2 (ignored)
Running backend with autologin
LANGFLOW_AUTO_LOGIN=True poetry run langflow run --backend-only --port 7860 --host 0.0.0.0 --no-open-browser --env-file .env
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/battlecruser/micromamba/envs/langconda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/__init__.py", line 5, in <module>
    from langflow.processing.process import load_flow_from_json
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/processing/process.py", line 10, in <module>
    from langflow.graph import Graph
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/graph/__init__.py", line 2, in <module>
    from langflow.graph.graph.base import Graph
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/graph/graph/base.py", line 7, in <module>
    from langflow.graph.graph.constants import lazy_load_vertex_dict
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/graph/graph/constants.py", line 1, in <module>
    from langflow.graph.vertex import types
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/graph/vertex/types.py", line 5, in <module>
    from langflow.graph.vertex.base import Vertex
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/graph/vertex/base.py", line 9, in <module>
    from langflow.interface.initialize import loading
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/interface/initialize/loading.py", line 17, in <module>
    from langflow.interface.custom_lists import CUSTOM_NODES
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/interface/custom_lists.py", line 7, in <module>
    from langflow.interface.agents.custom import CUSTOM_AGENTS
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/interface/agents/__init__.py", line 1, in <module>
    from langflow.interface.agents.base import AgentCreator
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/interface/agents/base.py", line 5, in <module>
    from langflow.custom.customs import get_custom_nodes
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/custom/customs.py", line 1, in <module>
    from langflow.template import frontend_node
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/template/frontend_node/__init__.py", line 1, in <module>
    from langflow.template.frontend_node import (
  File "/home/battlecruser/.local/lib/python3.9/site-packages/langflow/template/frontend_node/memories.py", line 7, in <module>
    from langchain.memory.chat_message_histories.postgres import DEFAULT_CONNECTION_STRING
ImportError: cannot import name 'DEFAULT_CONNECTION_STRING' from 'langchain.memory.chat_message_histories.postgres' (/home/battlecruser/micromamba/envs/langconda/lib/python3.9/site-packages/langchain/memory/chat_message_histories/postgres.py)
make: *** [Makefile:74: backend] Error 1

```

**Comment by ogabrielluiz** [comment]
Hey, @yamonkjd 

We are in the process of updating to Langchain 0.1 in the branch `update_lc`.

Since there are a lot of changes we are migrating all components to the CustomComponent framework first which will probably be ready beginning of next week.

We'll probably open a draft PR to make it easier to follow the progress.

**Comment by yamonkjd** [comment]
> Hey, @yamonkjd
> 
> We are in the process of updating to Langchain 0.1 in the branch `update_lc`.
> 
> Since there are a lot of changes we are migrating all components to the CustomComponent framework first which will probably be ready beginning of next week.
> 
> We'll probably open a draft PR to make it easier to follow the progress.

Thank you for answer. That's really cool
