### ISSUE TITLE
Frontend build error

### ISSUE THREAD

**Issue by artemus717** [logspace-ai/langflow#1392]
**Describe the bug**
#12 [frontend_build 6/6] RUN npm run build
#12       digest: sha256:93031358cd3c8505165dee0306c5c97c75bfcd74584f96cf42a28b67ceccf367
#12         name: "[frontend_build 6/6] RUN npm run build"
#12      started: 2024-02-05 00:40:49.615778007 +0000 UTC
#12 1.074 
#12 1.074 > langflow@0.1.2 build
#12 1.074 > vite build
#12 1.074 
#12 1.681 vite v4.5.1 building for production...
#12 1.793 <script src="/node_modules/ace-builds/src-min-noconflict/ace.js"> in "/index.html" can't be bundled without type="module" attribute
#12 1.800 transforming...
#12 1.860 ✓ 2 modules transformed.
#12 1.861 ✓ built in 177ms
#12 1.861 [vite]: Rollup failed to resolve import "/src/index.tsx" from "/app/index.html".
#12 1.861 This is most likely unintended because it can break your application at runtime.
#12 1.861 If you do want to externalize this module explicitly add it to
#12 1.861 `build.rollupOptions.external`
#12 1.865 error during build:
#12 1.865 Error: [vite]: Rollup failed to resolve import "/src/index.tsx" from "/app/index.html".
#12 1.865 This is most likely unintended because it can break your application at runtime.
#12 1.865 If you do want to externalize this module explicitly add it to
#12 1.865 `build.rollupOptions.external`
#12 1.865     at viteWarn (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:48216:27)
#12 1.865     at onwarn (/app/node_modules/@vitejs/plugin-react-swc/index.cjs:197:9)
#12 1.865     at onRollupWarning (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:48245:9)
#12 1.865     at onwarn (file:///app/node_modules/vite/dist/node/chunks/dep-68d1a114.js:47976:13)
#12 1.865     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
#12 1.865     at Object.logger [as onLog] (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
#12 1.865     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
#12 1.865     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
#12    completed: 2024-02-05 00:40:51.621635295 +0000 UTC
#12     duration: 2.005857288s
#12        error: "executor failed running [/bin/sh -c npm run build]: exit code: 1"

**Version**
 - 0.6.4

**Additional context**
I clone this repository and build with Jenkins. Changed dockerfile as this, because there maybe file path issue with origin frontend dockerfile.

FROM node:20-alpine as frontend_build
ARG BACKEND_URL
WORKDIR /app

COPY src/frontend/package.json src/frontend/package-lock.json src/frontend/tsconfig.json src/frontend/vite.config.ts src/frontend/index.html src/frontend/tailwind.config.js src/frontend/postcss.config.js src/frontend/prettier.config.js /app/
RUN npm install
COPY ./src /app/src
RUN npm run build

FROM nginx
COPY --from=frontend_build /app/build/ /usr/share/nginx/html
COPY src/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY src/frontend/start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh
ENV BACKEND_URL=$BACKEND_URL
CMD ["/start-nginx.sh"]

**Comment by artemus717** [comment]
Can you confirm if the file /src/index.tsx exists in your local repository and if it's correctly referenced in /app/index.html?
index.tsx seemd in src/frontend/src direcotyr
Have you made any changes to the vite.config.ts or tsconfig.json files?
Cloned from 0.6.4
Could you share the content of your vite.config.ts and tsconfig.json files?
Cloned from 0.6.4
Are there any specific steps you're following before running the build command?
No

**Comment by artemus717** [comment]
Changed dockerfile path, build success

FROM node:20-alpine as frontend_build
ARG BACKEND_URL
WORKDIR /app

COPY src/frontend/package.json src/frontend/package-lock.json src/frontend/tsconfig.json src/frontend/vite.config.ts src/frontend/index.html src/frontend/tailwind.config.js src/frontend/postcss.config.js src/frontend/prettier.config.js /app/
RUN npm install
COPY src/frontend/src /app/src
RUN npm run build

FROM nginx
COPY --from=frontend_build /app/build/ /usr/share/nginx/html
COPY src/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY src/frontend/start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh
ENV BACKEND_URL=$BACKEND_URL
CMD ["/start-nginx.sh"]
