### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by kusharma** [logspace-ai/langflow#1393]
**Describe the bug**

**Browser and Version**
Google chrome Version 121.0.6167.139 (Official Build) (x86_64)

**Error**
metadata-generation-failed
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 80, in __getattr__
          return next(
                 ^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 81, in <genexpr>
          ast.literal_eval(value)
        File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x106bac040>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 192, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 86, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/imackunal/Library/CloudStorage/GoogleDrive-kunal.nit90@gmail.com/My Drive/Data Engineering/GenAI/Langflow/langchain_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/imackunal/Library/CloudStorage/GoogleDrive-kunal.nit90@gmail.com/My Drive/Data Engineering/GenAI/Langflow/langchain_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/imackunal/Library/CloudStorage/GoogleDrive-kunal.nit90@gmail.com/My Drive/Data Engineering/GenAI/Langflow/langchain_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 623, in parse_config_files
          setupcfg.parse_configuration(
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 592, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 195, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-build-env-to_dwjop/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 215, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-install-ztxeyhpg/wrapt_e4ed8b26714e4a9a9d46dae4195ae293/src/wrapt/__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "/private/var/folders/gm/nk2nnfrx6ps02tz1gz8y51yr0000gn/T/pip-install-ztxeyhpg/wrapt_e4ed8b26714e4a9a9d46dae4195ae293/src/wrapt/decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
<img width="1356" alt="Error1" src="https://github.com/logspace-ai/langflow/assets/11337631/43957d42-5c23-41d0-afd8-86e750b243ec">
<img width="1356" alt="Error2" src="https://github.com/logspace-ai/langflow/assets/11337631/81cb3fcf-4891-4275-9dca-2759003d9ef3">

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by kusharma** [comment]
@dosu-but, Thanks a lot. it worked.

**Comment by Lee-So91** [comment]
@kusharma what was the issue and how were you able to fix it ?
