### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#1472]
![image](https://github.com/logspace-ai/langflow/assets/141118378/59627d84-de63-444c-9325-ce05714a9106)

I executed my project using the command `docker compose up --build`. When I try to access it through port 3000, I encounter an error. How should I proceed to run it correctly?

langflow-backend-1 | INFO: Started server process [7]
langflow-backend-1 | INFO: Waiting for application startup.
langflow-backend-1 | ERROR: Traceback (most recent call last):
langflow-backend-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
langflow-backend-1 | async with self.lifespan_context(app) as maybe_state:
langflow-backend-1 | File "/usr/local/lib/python3.10/contextlib.py", line 199, in aenter
langflow-backend-1 | return await anext(self.gen)
langflow-backend-1 | File "/app/src/backend/langflow/main.py", line 20, in lifespan
langflow-backend-1 | initialize_services()
langflow-backend-1 | File "/app/src/backend/langflow/services/utils.py", line 200, in initialize_services
langflow-backend-1 | service_manager.get(ServiceType.CACHE_SERVICE)
langflow-backend-1 | File "/app/src/backend/langflow/services/manager.py", line 40, in get
langflow-backend-1 | self._create_service(service_name)
langflow-backend-1 | File "/app/src/backend/langflow/services/manager.py", line 61, in _create_service
langflow-backend-1 | self.services[service_name].set_ready()
langflow-backend-1 | AttributeError: 'NoneType' object has no attribute 'set_ready'
langflow-backend-1 |
langflow-backend-1 | ERROR: Application startup failed. Exiting.

**Comment by yamonkjd** [comment]
Our developer found that it was a different issue; it was confirmed that cookies do not persist when operated on a server without SSL, preventing normal operation.
