### ISSUE TITLE
permission denied for schema public

### ISSUE THREAD

**Issue by maogeigei** [logspace-ai/langflow#1594]
[04/04/24 00:17:35] ERROR    2024-04-04 00:17:35 - ERROR    - service - Error creating table user:        service.py:233
                             (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
                             LINE 2: CREATE TABLE "user" (
                                                  ^

                             [SQL:
                             CREATE TABLE "user" (
                                     id UUID NOT NULL,
                                     username VARCHAR NOT NULL,
                                     password VARCHAR NOT NULL,
                                     profile_image VARCHAR,
                                     is_active BOOLEAN NOT NULL,
                                     is_superuser BOOLEAN NOT NULL,
                                     create_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     last_login_at TIMESTAMP WITHOUT TIME ZONE,
                                     store_api_key VARCHAR,
                                     PRIMARY KEY (id),
                                     UNIQUE (id)
                             )
 ]
                             (Background on this error at: https://sqlalche.me/e/20/f405)
                    ERROR    2024-04-04 00:17:35 - ERROR    - utils - Error creating DB and tables: Error    utils.py:24
                             creating table user
                    ERROR    2024-04-04 00:17:35 - ERROR    - utils - Error creating DB and tables          utils.py:216
[2024-04-04 00:17:35 +0800] [120110] [ERROR] Traceback (most recent call last):
  File "/home/llms/miniconda3/envs/dify/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/home/llms/miniconda3/envs/dify/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2: CREATE TABLE "user" (
The above exception was the direct cause of the following exception:

**Comment by maogeigei** [comment]
this helps thanks alot
