### ISSUE TITLE
Error: 'gbk' codec can't decode byte 0xa6 in position 4: illegal multibyte sequence

### ISSUE THREAD

**Issue by paladinlp** [logspace-ai/langflow#187]
Describe the bug
Im trying to install LangFlow with pip but i get an error

Browser and Version

- Win 10

- VS Code - most recent version

- pip 23.1 from C:\Python310\lib\site-packages\pip (python 3.10)

- Python 3.10

- pip install langflow

- installation fails

error :
 Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\test\anaconda3\envs\langflow\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\test\anaconda3\envs\langflow\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\test\anaconda3\envs\langflow\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-6sipyj6r\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-6sipyj6r\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\test\AppData\Local\Temp\pip-build-env-6sipyj6r\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Users\test\anaconda3\envs\langflow\lib\pathlib.py", line 1135, in read_text
          return f.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 4: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lxl876** [comment]
You can try setting the system variable PYTHONUTF8=1, it might help @paladinlp

**Comment by RuthlessXdream** [comment]
@lxl876 Thank you for your help. The problem has been solved.
