### ISSUE TITLE
ERROR:    Exception in ASGI application  websockets

### ISSUE THREAD

**Issue by rui-hai** [logspace-ai/langflow#265]
> langflow

[22:33:35] INFO     [22:33:35] - INFO - Logger set up with log level: 20(info)                                         logger.py:28
           INFO     [22:33:35] - INFO - Log file: logs/langflow.log                                                    logger.py:30
INFO:     Started server process [97396]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/ruihai/Library/Python/3.9/lib/python/site-packages/starlette/staticfiles.py", line 96, in __call__
    assert scope["type"] == "http"
AssertionError

**Comment by eugali** [comment]
same issue

**Comment by ogabrielluiz** [comment]
Hi, 
There's not much context to what happened. Could you follow the Bug template, please?

**Comment by rui-hai** [comment]
> Hi, There's not much context to what happened. Could you follow the Bug template, please?

I installed it locally, and after the installation is completed, I started it using the command and reported the error above.I asked my friends and they also made the same mistake
```
langflow
```
