### ISSUE TITLE
Not able to open langflow after installing

### ISSUE THREAD

**Issue by contemplatorNET** [logspace-ai/langflow#28]
(venv) PS C:\Users\XXX\PycharmProjects\XXX> langflow            
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\PycharmProjects\XXX\venv\Scripts\langflow.exe\__main__.py", line 4, in <module>
  File "C:\Users\XXX\PycharmProjects\XXX\venv\lib\site-packages\langflow_backend\__init__.py", line 1, in <module>
    from langflow_backend.interface.loading import load_flow_from_json  # noqa
  File "C:\Users\XXX\PycharmProjects\XXX\venv\lib\site-packages\langflow_backend\interface\loading.py", line 4, in <module>
    from langchain.agents.loading import load_agent_executor_from_config
ImportError: cannot import name 'load_agent_executor_from_config' from 'langchain.agents.loading' (C:\Users\XXX\PycharmProjects\XXX\venv\lib\site-packages\langchain\agents\loading.py)
(venv) PS C:\Users\XXX\PycharmProjects\XXX>

**Comment by ogabrielluiz** [comment]
@ibiscp Could you take a look at this?

**Comment by ibiscp** [comment]
Did you create a new environment?

Try this:

```
python -m venv .langflow
source .langflow/bin/activate
pip install langflow
langflow
```

**Comment by contemplatorNET** [comment]
the command "source .langflow/bin/activate" did not work I used ".\.langflow\Scripts\activate" that seems to work.
installing works as well
but when I want to start "langflow" i get an error message again. that the 'fcntl' module is missing. it seems like it is an windows related issue.

File "C:\Users\danie\PycharmProjects\XXX\.langflow\Scripts\langflow.exe\__main__.py", line 7, in <module>
    sys.exit(main())

  File "C:\Users\danie\PycharmProjects\XXX\.langflow\lib\site-packages\langflow_backend\__main__.py", line 51, in main
    typer.run(serve)

  File "C:\Users\danie\PycharmProjects\XXX\.langflow\lib\site-packages\langflow_backend\__main__.py", line 45, in serve
    from langflow_backend.server import LangflowApplication

  File "C:\Users\danie\PycharmProjects\XXX\.langflow\lib\site-packages\langflow_backend\server.py", line 1, in <module>
    from gunicorn.app.base import BaseApplication  # type: ignore

  File "C:\Users\danie\PycharmProjects\XXX\.langflow\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util

  File "C:\Users\danie\PycharmProjects\XXX\.langflow\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl

ModuleNotFoundError: No module named 'fcntl'
