### ISSUE TITLE
spawn.py Error - 

### ISSUE THREAD

**Issue by apontcai** [logspace-ai/langflow#502]
Could not run Langflow at all.

 - Windows 11
 - Python 3.10.11 (64 bit)
 - LangChain 0.0.202

**Error Msg**
C:\Users\xxxx>langflow
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 272, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 419, in load
    obj = StockUnpickler.load(self)
EOFError: Ran out of input
..................................
PicklingError: Can't pickle <cyfunction str_validator at 0x000002857FE7CEE0>: it's not the same object as
pydantic.validators.str_validator

**Screenshots**
![Screenshot 2023-06-17 225126](https://github.com/logspace-ai/langflow/assets/29941434/c16cca7e-27d7-487f-837b-4c7d78d24143)

**Comment by mindwellsolutions** [comment]
I have the same issue. Any solutions? This installs on ubuntu fine, but on my windows 10 machine getting this error even in a conda langflow environment.

**Comment by onexixi** [comment]
me too

**Comment by ogabrielluiz** [comment]
Hey all. 
Thanks for the feedback. We'll try to fix this ASAP

**Comment by ogabrielluiz** [comment]
Let me know if this is working now, please.

**Comment by mindwellsolutions** [comment]
Langchain is working now on Windows 10 for me after newest fix. Thank you!
