### ISSUE TITLE
jcloud deployment failed

### ISSUE THREAD

**Issue by callzhang** [logspace-ai/langflow#507]
**Describe the bug**
jcloud deployment failed

**To Reproduce**
```python
~ langflow --jcloud
🚀 Deploying Langflow server on Jina AI Cloud
JCloud config file at app directory will be applied: /Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/jcloud.yml
Unexpected phase: Failed reached at Starting for Flow ID langflow-3b04530202
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<serve_on_jcloud() done, defined at /Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/__main__.py:52> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/core.py", line 716, in main
    return _main(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/__main__.py", line 127, in serve
    return serve_on_jcloud()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/__main__.py", line 71, in serve_on_jcloud
    app_id = asyncio.run(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 84, in run_until_complete
    self._run_once()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 120, in _run_once
    handle._run()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/__main__.py", line 94, in serve_on_jcloud
    app_id, _ = await deploy_app_on_jcloud(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/flow.py", line 621, in deploy_app_on_jcloud
    jcloud_flow = await CloudFlow(path=flow_path).__aenter__()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 536, in __aenter__
    self.endpoints, self.dashboard = await self._fetch_until(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 487, in _fetch_until
    _exit_error(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 69, in _exit_error
    exit(1)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
(python310)  ✘  ~  langflow --jcloud
🚀 Deploying Langflow server on Jina AI Cloud
JCloud config file at app directory will be applied: /Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/jcloud.yml
Unexpected phase: Failed reached at Starting for Flow ID langflow-e66fd52977
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<serve_on_jcloud() done, defined at /Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/__main__.py:52> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/core.py", line 716, in main
    return _main(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/__main__.py", line 127, in serve
    return serve_on_jcloud()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/langflow/__main__.py", line 71, in serve_on_jcloud
    app_id = asyncio.run(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 84, in run_until_complete
    self._run_once()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 120, in _run_once
    handle._run()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/__main__.py", line 94, in serve_on_jcloud
    app_id, _ = await deploy_app_on_jcloud(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/lcserve/flow.py", line 621, in deploy_app_on_jcloud
    jcloud_flow = await CloudFlow(path=flow_path).__aenter__()
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 536, in __aenter__
    self.endpoints, self.dashboard = await self._fetch_until(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 487, in _fetch_until
    _exit_error(
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/site-packages/jcloud/flow.py", line 69, in _exit_error
    exit(1)
  File "/Users/derek/miniforge3/envs/python310/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Screenshots**

**Additional context**
MacOS conda python 3.10

**Comment by zac-li** [comment]
Hey what's your langflow pypi version? I'm from `jcloud` team.
