### ISSUE TITLE
Process stuck

### ISSUE THREAD

**Issue by ubuntudroid** [logspace-ai/langflow#67]
I've installed `langflow` via pip on my Mac and ran it using `langflow`. But it seems to be stuck. I get the following when `CTRL-C`ing out of the process.

```
Traceback (most recent call last):
  File "/usr/local/bin/langflow", line 5, in <module>
    from langflow.__main__ import main
  File "/usr/local/lib/python3.11/site-packages/langflow/__init__.py", line 1, in <module>
    from langflow.interface.loading import load_flow_from_json  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langflow/interface/loading.py", line 3, in <module>
    from langflow.interface.types import get_type_list
  File "/usr/local/lib/python3.11/site-packages/langflow/interface/types.py", line 1, in <module>
    from langflow.interface.listing import list_type
  File "/usr/local/lib/python3.11/site-packages/langflow/interface/listing.py", line 1, in <module>
    from langchain import chains, agents, prompts
  File "/usr/local/lib/python3.11/site-packages/langchain/__init__.py", line 57, in <module>
    set_default_callback_manager()
  File "/usr/local/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 31, in set_default_callback_manager
    set_tracing_callback_manager(session)
  File "/usr/local/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 45, in set_tracing_callback_manager
    handler.load_default_session()
  File "/usr/local/lib/python3.11/site-packages/langchain/callbacks/tracers/langchain.py", line 83, in load_default_session
    r = requests.get(
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ogabrielluiz** [comment]
This does not seem to be a LangFlow bug. 
Technically, if you imported LangChain you'd encounter the same error. 
Have you tried it?

**Comment by ubuntudroid** [comment]
Alright, it was the langchain tracer. I had `LANGCHAIN_HANDLER=langchain` environment variable set and apparently that's what's blocking everything.

Removing the environment variable fixed everything.
