### ISSUE TITLE
Error while running docker compose: FAILED: /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/vendor/llama.cpp/libllama.so 

### ISSUE THREAD

**Issue by 3eif** [logspace-ai/langflow#701]
I get the following error when I run `docker compose up --build` on macos.

I've already tried installed build-essentials.

```
langflow % docker compose up --build

[+] Building 51.1s (27/27) FINISHED                                                                                                                                         
 => [backend internal] load build definition from dev.Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 708B                                                                                                                                   0.0s
 => [backend internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [backend internal] load metadata for docker.io/library/python:3.10-slim                                                                                            0.5s
 => [frontend internal] load build definition from dev.Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 708B                                                                                                                                   0.0s
 => [frontend internal] load .dockerignore                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                        0.0s
 => [frontend internal] load metadata for docker.io/library/node:19-bullseye-slim                                                                                      0.5s
 => [frontend base 1/5] FROM docker.io/library/node:19-bullseye-slim@sha256:f58f1fcf5c9ff9e3752993edb4ed6dbd35697124c85a43f3b97aa054500b0534                           0.0s
 => [frontend internal] load build context                                                                                                                             0.0s
 => => transferring context: 31.35kB                                                                                                                                   0.0s
 => [backend 1/7] FROM docker.io/library/python:3.10-slim@sha256:84ecab4ecf38604b04bfb8623d9159b863afe154f74c41350c619fa2470e0ef0                                      0.0s
 => [backend internal] load build context                                                                                                                              0.2s
 => => transferring context: 491.92kB                                                                                                                                  0.2s
 => CACHED [frontend base 2/5] RUN mkdir -p /home/node/app                                                                                                             0.0s
 => CACHED [frontend base 3/5] RUN chown -R node:node /home/node && chmod -R 770 /home/node                                                                            0.0s
 => CACHED [frontend base 4/5] RUN apt-get update && apt-get install -y jq                                                                                             0.0s
 => CACHED [frontend base 5/5] WORKDIR /home/node/app                                                                                                                  0.0s
 => CACHED [frontend builder-client 1/6] RUN echo "BACKEND_URL: http://backend:7860"                                                                                   0.0s
 => CACHED [frontend builder-client 2/6] WORKDIR /home/node/app                                                                                                        0.0s
 => CACHED [frontend builder-client 3/6] COPY --chown=node:node . ./                                                                                                   0.0s
 => CACHED [frontend builder-client 4/6] COPY ./set_proxy.sh .                                                                                                         0.0s
 => CACHED [frontend builder-client 5/6] RUN chmod +x set_proxy.sh &&     cat set_proxy.sh | tr -d '\r' > set_proxy_unix.sh &&     chmod +x set_proxy_unix.sh &&       0.0s
 => CACHED [frontend builder-client 6/6] RUN npm install --loglevel warn                                                                                               0.0s
 => [frontend] exporting to image                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                0.0s
 => => writing image sha256:b4c3c42528d91f6f9d97b378fb4b6b8846850aff69a9a492f8dccef15fd02108                                                                           0.0s
 => => naming to docker.io/library/langflow-frontend                                                                                                                   0.0s
 => CACHED [backend 2/7] WORKDIR /app                                                                                                                                  0.0s
 => CACHED [backend 3/7] RUN apt-get update && apt-get install gcc g++ curl build-essential postgresql-server-dev-all -y                                               0.0s
 => CACHED [backend 4/7] RUN curl -sSL https://install.python-poetry.org | python3 -                                                                                   0.0s
 => CACHED [backend 5/7] COPY poetry.lock pyproject.toml ./                                                                                                            0.0s
 => CACHED [backend 6/7] COPY ./ ./                                                                                                                                    0.0s
 => ERROR [backend 7/7] RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi                                                       50.4s
------
 > [backend 7/7] RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi:
0.594 Skipping virtualenv creation, as specified in config file.
0.652 Installing dependencies from lock file
1.540 
1.540 Package operations: 289 installs, 1 update, 0 removals
1.540 
1.540   • Installing pycparser (2.21)
1.541   • Installing wrapt (1.15.0)
1.541   • Installing zipp (3.16.2)
1.883   • Installing certifi (2023.7.22)
1.884   • Installing cffi (1.15.1)
1.886   • Installing deprecated (1.2.14)
1.887   • Installing charset-normalizer (3.2.0)
1.888   • Installing idna (3.4)
1.890   • Installing importlib-metadata (6.8.0)
1.890   • Installing mdurl (0.1.2)
1.891   • Installing multidict (6.0.4)
1.892   • Installing frozenlist (1.4.0)
1.923   • Installing protobuf (3.20.3)
1.938   • Installing pyasn1 (0.5.0)
2.024   • Installing six (1.16.0)
2.045   • Installing urllib3 (1.26.16)
2.284   • Installing aiosignal (1.3.1)
2.285   • Installing async-timeout (4.0.2)
2.285   • Installing attrs (23.1.0)
2.286   • Installing cachetools (5.3.1)
2.287   • Installing cryptography (41.0.2)
2.287   • Installing ecdsa (0.18.0)
2.288   • Installing exceptiongroup (1.1.2)
2.289   • Installing jeepney (0.8.0)
2.289   • Installing markdown-it-py (3.0.0)
2.325   • Installing more-itertools (9.1.0)
2.347   • Installing opentelemetry-api (1.19.0)
2.353   • Installing opentelemetry-proto (1.19.0)
2.369   • Installing opentelemetry-semantic-conventions (0.40b0)
2.376   • Installing packaging (23.1)
2.386   • Installing pyasn1-modules (0.3.0)
2.409   • Installing pygments (2.15.1)
2.417   • Installing requests (2.31.0)
2.462   • Installing rsa (4.9)
2.527   • Updating setuptools (65.5.1 -> 68.0.0)
2.593   • Installing sniffio (1.3.0)
2.596   • Installing typing-extensions (4.5.0)
2.598   • Installing webencodings (0.5.1)
2.607   • Installing websocket-client (1.6.1)
2.615   • Installing yarl (1.9.2)
3.704   • Installing aiohttp (3.8.5)
3.705   • Installing anyio (3.7.1)
3.705   • Installing asgiref (3.7.2)
3.706   • Installing bleach (6.0.0)
3.707   • Installing docker (6.1.3)
3.708   • Installing backoff (2.2.1)
3.708   • Installing docutils (0.20.1)
3.709   • Installing filelock (3.12.2)
3.710   • Installing google-auth (2.22.0)
3.750   • Installing googleapis-common-protos (1.59.1)
3.753   • Installing grpcio (1.47.5)
3.806   • Installing h11 (0.14.0)
3.893   • Installing jaraco-classes (3.3.0)
3.970   • Installing markupsafe (2.1.3)
3.978   • Installing mpmath (1.3.0)
3.990   • Installing mypy-extensions (1.0.0)
3.991   • Installing opentelemetry-exporter-otlp-proto-common (1.19.0)
4.004   • Installing opentelemetry-instrumentation (0.40b0)
4.094   • Installing opentelemetry-sdk (1.19.0)
4.123   • Installing opentelemetry-util-http (0.40b0)
4.125   • Installing pathspec (0.11.1)
4.137   • Installing python-jose (3.3.0)
4.215   • Installing pyyaml (6.0.1)
4.226   • Installing rich (13.4.2)
4.261   • Installing secretstorage (3.3.3)
4.297   • Installing smmap (5.0.0)
7.631   • Installing asttokens (2.2.1)
7.632   • Installing click (8.1.6)
7.633   • Installing colorama (0.4.6)
7.633   • Installing fsspec (2023.6.0)
7.634   • Installing executing (1.2.0)
7.635   • Installing gitdb (4.0.10)
7.635   • Installing google-api-core (2.11.1)
7.637   • Installing google-crc32c (1.5.0)
7.638   • Installing greenlet (2.0.2)
7.728   • Installing grpcio-status (1.47.5)
7.758   • Installing hpack (4.0.0)
7.772   • Installing httpcore (0.16.3)
7.775   • Installing httptools (0.6.0)
7.779   • Installing humanfriendly (10.0)
7.799   • Installing hyperframe (6.0.1)
7.816   • Installing jina-hubble-sdk (0.39.0)
7.866   • Installing jinja2 (3.1.2)
7.895   • Installing keyring (24.2.0)
7.900   • Installing marshmallow (3.20.1)
7.901   • Installing networkx (3.1)
7.935   • Installing numpy (1.25.1)
7.994   • Installing opentelemetry-exporter-otlp-proto-grpc (1.19.0)
8.034   • Installing opentelemetry-exporter-otlp-proto-http (1.19.0)
8.039   • Installing opentelemetry-instrumentation-asgi (0.40b0)
8.059   • Installing parso (0.8.3)
8.069   • Installing pkginfo (1.9.6)
8.076   • Installing platformdirs (3.9.1)
8.113   • Installing prometheus-client (0.17.1)
8.129   • Installing ptyprocess (0.7.0)
8.141   • Installing pure-eval (0.2.2)
8.219   • Installing pydantic (1.10.11)
8.237   • Installing pyparsing (3.1.0)
8.265   • Installing python-dateutil (2.8.2)
8.279   • Installing python-dotenv (1.0.0)
8.281   • Installing readme-renderer (40.0)
8.316   • Installing requests-toolbelt (1.0.0)
8.318   • Installing rfc3986 (1.5.0)
8.390   • Installing starlette (0.27.0)
8.411   • Installing sympy (1.12)
8.412   • Installing tqdm (4.65.0)
8.466   • Installing traitlets (5.9.0)
8.471   • Installing typing-inspect (0.9.0)
8.485   • Installing uvloop (0.17.0)
8.498   • Installing watchfiles (0.19.0)
8.578   • Installing wcwidth (0.2.6)
8.591   • Installing websockets (10.4)
10.01   • Installing aiofiles (23.1.0)
10.01   • Installing aiostream (0.4.5)
10.01   • Installing backcall (0.2.0)
10.01   • Installing click-log (0.4.0)
10.02   • Installing coloredlogs (15.0.1)
10.02   • Installing decorator (5.1.1)
10.02   • Installing dataclasses-json (0.5.13)
10.02   • Installing deprecation (2.1.0)
10.02   • Installing docarray (0.21.1)
10.11   • Installing dotty-dict (1.3.1)
10.12   • Installing et-xmlfile (1.1.0)
10.12   • Installing fastapi (0.100.0)
10.13   • Installing flatbuffers (23.5.26)
10.13   • Installing gitpython (3.1.32)
10.13   • Installing google-cloud-core (2.3.3)
10.14   • Installing google-resumable-media (2.5.0)
10.15   • Installing grpc-google-iam-v1 (0.12.6)
10.17   • Installing grpcio-health-checking (1.47.5)
10.22   • Installing grpcio-reflection (1.47.5)
10.23   • Installing h2 (4.1.0)
10.27   • Installing httplib2 (0.22.0)
10.28   • Installing httpx (0.23.3)
10.29   • Installing huggingface-hub (0.15.1)
10.29   • Installing iniconfig (2.0.0)
10.33   • Installing invoke (1.7.3)
10.34   • Installing jcloud (0.2.12)
10.37   • Installing jedi (0.18.2)
10.39   • Installing joblib (1.3.1)
10.40   • Installing jupyter-core (5.3.1)
10.40   • Installing langsmith (0.0.14)
10.43   • Installing lxml (4.9.3)
10.60   • Installing lz4 (4.3.2)
10.61   • Installing matplotlib-inline (0.1.6)
10.68   • Installing monotonic (1.6)
10.69   • Installing numexpr (2.8.4)
10.75   • Installing olefile (0.46)
10.81   • Installing openapi-schema-pydantic (1.2.4)
11.00   • Installing opentelemetry-exporter-otlp (1.19.0)
11.06   • Installing opentelemetry-exporter-prometheus (1.12.0rc1)
11.10   • Installing opentelemetry-instrumentation-aiohttp-client (0.40b0)
11.15   • Installing opentelemetry-instrumentation-fastapi (0.40b0)
11.19   • Installing opentelemetry-instrumentation-grpc (0.40b0)
11.36   • Installing pexpect (4.8.0)
11.36   • Installing pickleshare (0.7.5)
11.37   • Installing pillow (10.0.0)
11.40   • Installing pluggy (1.2.0)
11.51   • Installing prompt-toolkit (3.0.39)
11.54   • Installing proto-plus (1.22.3)
11.59   • Installing python-gitlab (3.15.0)
11.73   • Installing python-multipart (0.0.6)
11.95   • Installing pytz (2023.3)
11.97   • Installing pyzmq (25.1.0)
12.18   • Installing regex (2023.6.3)
12.54   • Installing safetensors (0.3.1)
12.67   • Installing scipy (1.11.1)
12.78   • Installing semver (2.13.0)
12.86   • Installing soupsieve (2.4.1)
12.98   • Installing sqlalchemy (1.4.41)
12.99   • Installing stack-data (0.6.2)
13.00   • Installing strenum (0.4.15)
13.10   • Installing tenacity (8.2.2)
13.13   • Installing threadpoolctl (3.2.0)
13.14   • Installing tokenizers (0.13.3)
13.24   • Installing tomli (2.0.1)
13.28   • Installing tomlkit (0.11.8)
13.37   • Installing torch (2.0.1)
13.39   • Installing tornado (6.3.2)
13.43   • Installing twine (3.8.0)
13.50   • Installing tzdata (2023.3)
13.71   • Installing uvicorn (0.22.0)
13.73   • Installing xlsxwriter (3.1.2)
13.96   • Installing zstandard (0.21.0)
20.18   • Installing argilla (0.0.1)
20.18   • Installing authlib (1.2.1)
20.18   • Installing beautifulsoup4 (4.12.2)
20.18   • Installing chardet (5.1.0)
20.18   • Installing comm (0.1.3)
20.18   • Installing clickhouse-connect (0.6.8)
20.18   • Installing coverage (7.2.7)
20.19   • Installing debugpy (1.6.7)
20.19   • Installing dill (0.3.7)
20.26   • Installing diskcache (5.6.1)
20.28   • Installing distro (1.8.0)
20.40   • Installing dnspython (2.3.0)
20.41   • Installing duckdb (0.8.1)
20.41   • Installing filetype (1.2.0)
20.42   • Installing google-auth-httplib2 (0.1.0)
20.45   • Installing google-cloud-bigquery (3.11.4)
20.51   • Installing google-cloud-resource-manager (1.10.2)
20.52   • Installing google-cloud-storage (2.10.0)
20.59   • Installing gotrue (1.0.2)
20.70   • Installing grpcio-tools (1.47.5)
20.77   • Installing hnswlib (0.7.0)
20.78   • Installing ipython (8.14.0)
20.78   • Installing jina (3.15.2)
20.80   • Installing jupyter-client (8.3.0)
20.91   • Installing langchain (0.0.240)
20.95   • Installing loguru (0.7.0)
21.11   • Installing markdown (3.4.3)
21.20   • Installing msg-parser (1.2.0)
21.32   • Installing nest-asyncio (1.5.6)
21.41   • Installing nltk (3.8.1)
21.45   • Installing onnxruntime (1.15.1)
21.90   • Installing openpyxl (3.1.2)
22.56   • Installing overrides (7.3.1)
22.70   • Installing pandas (2.0.3)
23.05   • Installing pdf2image (1.16.3)
23.15   • Installing pdfminer-six (20221105)
23.18   • Installing portalocker (2.7.0)
23.29   • Installing postgrest (0.10.6)
23.47   • Installing posthog (3.0.1)
23.63   • Installing psutil (5.9.5)
23.91   • Installing pulsar-client (3.2.0)
24.10   • Installing pypandoc (1.11)
24.24   • Installing pytest (7.4.0)
24.66   • Installing python-docx (0.8.11)
24.97   • Installing python-magic (0.4.27)
25.18   • Installing python-pptx (0.6.21)
25.32   • Installing python-semantic-release (7.33.2)
25.36   • Installing realtime (1.0.0)
25.48   • Installing scikit-learn (1.3.0)
25.54   • Installing sentencepiece (0.1.99)
25.62   • Installing shapely (1.8.5.post1)
25.96   • Installing sqlalchemy2-stubs (0.0.2a35)
26.17   • Installing storage3 (0.5.2)
26.33   • Installing supafunc (0.2.2)
26.41   • Installing tabulate (0.9.0)
26.49   • Installing torchvision (0.15.2)
26.52   • Installing transformers (4.31.0)
27.02   • Installing types-pytz (2023.3.0.0)
27.14   • Installing types-urllib3 (1.26.25.14)
27.28   • Installing uritemplate (4.1.1)
27.37   • Installing validators (0.20.0)
27.38   • Installing xlrd (2.0.1)
39.52   • Installing anthropic (0.3.6)
39.52   • Installing appdirs (1.4.4)
39.52   • Installing black (23.7.0)
39.52   • Installing cohere (4.17.0)
39.52   • Installing docstring-parser (0.15)
39.52   • Installing ctransformers (0.2.14)
39.52   • Installing faiss-cpu (1.7.4)
39.52   • Installing chromadb (0.3.26)
39.53   • Installing fake-useragent (1.1.3)
39.60   • Installing google-api-python-client (2.94.0)
39.63   • Installing google-cloud-aiplatform (1.28.1)
39.65   • Installing google-search-results (2.4.2)
39.67   • Installing gunicorn (21.2.0)
39.71   • Installing ipykernel (6.24.0)
39.73   • Installing llama-cpp-python (0.1.74)
39.78   • Installing multiprocess (0.70.15)
40.04   • Installing mypy (1.4.1)
40.06   • Installing openai (0.27.8)
40.11   • Installing orjson (3.9.2)
40.29   • Installing pandas-stubs (2.0.2.230605)
40.30   • Installing pinecone-client (2.2.2)
40.66   • Installing psycopg (3.1.9)
40.91   • Installing psycopg-binary (3.1.9)
40.94   • Installing psycopg2-binary (2.9.6)
41.13   • Installing pyarrow (12.0.1)
41.21   • Installing pymongo (4.4.1)
41.65   • Installing pypdf (3.13.0)
41.77   • Installing pysrt (1.1.2)
41.89   • Installing pytest-cov (4.1.0)
42.01   • Installing qdrant-client (1.3.1)
42.03   • Installing ruff (0.0.254)
42.04   • Installing sentence-transformers (2.2.2)
42.37   • Installing sqlmodel (0.0.8)
42.47   • Installing supabase (1.0.3)
42.55   • Installing tiktoken (0.4.0)
42.73   • Installing typer (0.9.0)
42.88   • Installing types-appdirs (1.4.3.5)
43.04   • Installing types-cachetools (5.3.0.6)
43.09   • Installing types-pillow (9.5.0.6)
43.19   • Installing types-pyyaml (6.0.12.11)
43.25   • Installing types-requests (2.31.0.2)
43.28   • Installing unstructured (0.7.12)
43.30   • Installing weaviate-client (3.22.1)
43.33   • Installing wikipedia (1.4.0)
49.60 
49.60   ChefBuildError
49.60 
49.60   Backend subprocess exited when trying to invoke build_wheel
49.60   
49.60   
49.60   
49.60   --------------------------------------------------------------------------------
49.60   -- Trying 'Ninja' generator
49.60   --------------------------------
49.60   ---------------------------
49.60   ----------------------
49.60   -----------------
49.60   ------------
49.60   -------
49.60   --
49.60   CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
49.60     Compatibility with CMake < 3.5 will be removed from a future version of
49.60     CMake.
49.60   
49.60     Update the VERSION argument <min> value or use a ...<max> suffix to tell
49.60     CMake that the project does not need compatibility with older versions.
49.60   
49.60   Not searching for unused variables given on the command line.
49.60   
49.60   -- The C compiler identification is GNU 12.2.0
49.60   -- Detecting C compiler ABI info
49.60   -- Detecting C compiler ABI info - done
49.60   -- Check for working C compiler: /usr/bin/cc - skipped
49.60   -- Detecting C compile features
49.60   -- Detecting C compile features - done
49.60   -- The CXX compiler identification is GNU 12.2.0
49.60   -- Detecting CXX compiler ABI info
49.60   -- Detecting CXX compiler ABI info - done
49.60   -- Check for working CXX compiler: /usr/bin/c++ - skipped
49.60   -- Detecting CXX compile features
49.60   -- Detecting CXX compile features - done
49.60   -- Configuring done (0.2s)
49.60   -- Generating done (0.0s)
49.60   -- Build files have been written to: /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/_cmake_test_compile/build
49.60   --
49.60   -------
49.60   ------------
49.60   -----------------
49.60   ----------------------
49.60   ---------------------------
49.60   --------------------------------
49.60   -- Trying 'Ninja' generator - success
49.60   --------------------------------------------------------------------------------
49.60   
49.60   Configuring Project
49.60     Working directory:
49.60       /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/_skbuild/linux-aarch64-3.10/cmake-build
49.60     Command:
49.60       /tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/cmake/data/bin/cmake /tmp/tmpw53zyla9/llama_cpp_python-0.1.74 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tmpw53zyla9/llama_cpp_python-0.1.74/_skbuild/linux-aarch64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.12 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/tmp/tmpkx4o11sf/.venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/local/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/tmp/tmpkx4o11sf/.venv/bin/python -DPython_ROOT_DIR:PATH=/tmp/tmpkx4o11sf/.venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/usr/local/include/python3.10 -DPython3_EXECUTABLE:PATH=/tmp/tmpkx4o11sf/.venv/bin/python -DPython3_ROOT_DIR:PATH=/tmp/tmpkx4o11sf/.venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/usr/local/include/python3.10 -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
49.60   
49.60   Not searching for unused variables given on the command line.
49.60   -- The C compiler identification is GNU 12.2.0
49.60   -- The CXX compiler identification is GNU 12.2.0
49.60   -- Detecting C compiler ABI info
49.60   -- Detecting C compiler ABI info - done
49.60   -- Check for working C compiler: /usr/bin/cc - skipped
49.60   -- Detecting C compile features
49.60   -- Detecting C compile features - done
49.60   -- Detecting CXX compiler ABI info
49.60   -- Detecting CXX compiler ABI info - done
49.60   -- Check for working CXX compiler: /usr/bin/c++ - skipped
49.60   -- Detecting CXX compile features
49.60   -- Detecting CXX compile features - done
49.60   -- Configuring done (0.2s)
49.60   -- Generating done (0.0s)
49.60   -- Build files have been written to: /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/_skbuild/linux-aarch64-3.10/cmake-build
49.60   [1/2] Generating /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/vendor/llama.cpp/libllama.so
49.60   FAILED: /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/vendor/llama.cpp/libllama.so 
49.60   cd /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/vendor/llama.cpp && make libllama.so
49.60   I llama.cpp build info: 
49.60   I UNAME_S:  Linux
49.60   I UNAME_P:  unknown
49.60   I UNAME_M:  aarch64
49.60   I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_K_QUANTS -mcpu=native
49.60   I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS -mcpu=native
49.60   I LDFLAGS:  
49.60   I CC:       cc (Debian 12.2.0-14) 12.2.0
49.60   I CXX:      g++ (Debian 12.2.0-14) 12.2.0
49.60   
49.60   g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS -mcpu=native -c llama.cpp -o llama.o
49.60   cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_K_QUANTS -mcpu=native   -c ggml.c -o ggml.o
49.60   In file included from ggml.c:281:
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h: In function ‘ggml_vec_dot_f16’:
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h:29182:1: error: inlining failed in call to ‘always_inline’ ‘vfmaq_f16’: target specific option mismatch
49.60   29182 | vfmaq_f16 (float16x8_t __a, float16x8_t __b, float16x8_t __c)
49.60         | ^~~~~~~~~
49.60   ggml.c:1817:37: note: called from here
49.60    1817 |     #define GGML_F16x8_FMA(a, b, c) vfmaq_f16(a, b, c)
49.60         |                                     ^~~~~~~~~~~~~~~~~~
49.60   ggml.c:1844:41: note: in expansion of macro ‘GGML_F16x8_FMA’
49.60    1844 |     #define GGML_F16_VEC_FMA            GGML_F16x8_FMA
49.60         |                                         ^~~~~~~~~~~~~~
49.60   ggml.c:2341:22: note: in expansion of macro ‘GGML_F16_VEC_FMA’
49.60    2341 |             sum[j] = GGML_F16_VEC_FMA(sum[j], ax[j], ay[j]);
49.60         |                      ^~~~~~~~~~~~~~~~
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h:29182:1: error: inlining failed in call to ‘always_inline’ ‘vfmaq_f16’: target specific option mismatch
49.60   29182 | vfmaq_f16 (float16x8_t __a, float16x8_t __b, float16x8_t __c)
49.60         | ^~~~~~~~~
49.60   ggml.c:1817:37: note: called from here
49.60    1817 |     #define GGML_F16x8_FMA(a, b, c) vfmaq_f16(a, b, c)
49.60         |                                     ^~~~~~~~~~~~~~~~~~
49.60   ggml.c:1844:41: note: in expansion of macro ‘GGML_F16x8_FMA’
49.60    1844 |     #define GGML_F16_VEC_FMA            GGML_F16x8_FMA
49.60         |                                         ^~~~~~~~~~~~~~
49.60   ggml.c:2341:22: note: in expansion of macro ‘GGML_F16_VEC_FMA’
49.60    2341 |             sum[j] = GGML_F16_VEC_FMA(sum[j], ax[j], ay[j]);
49.60         |                      ^~~~~~~~~~~~~~~~
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h:28760:1: error: inlining failed in call to ‘always_inline’ ‘vaddq_f16’: target specific option mismatch
49.60   28760 | vaddq_f16 (float16x8_t __a, float16x8_t __b)
49.60         | ^~~~~~~~~
49.60   ggml.c:1824:20: note: called from here
49.60    1824 |             x[i] = vaddq_f16(x[i], x[offset+i]);                  \
49.60         |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
49.60   ggml.c:1847:41: note: in expansion of macro ‘GGML_F16x8_REDUCE’
49.60    1847 |     #define GGML_F16_VEC_REDUCE         GGML_F16x8_REDUCE
49.60         |                                         ^~~~~~~~~~~~~~~~~
49.60   ggml.c:2346:5: note: in expansion of macro ‘GGML_F16_VEC_REDUCE’
49.60    2346 |     GGML_F16_VEC_REDUCE(sumf, sum);
49.60         |     ^~~~~~~~~~~~~~~~~~~
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h:28760:1: error: inlining failed in call to ‘always_inline’ ‘vaddq_f16’: target specific option mismatch
49.60   28760 | vaddq_f16 (float16x8_t __a, float16x8_t __b)
49.60         | ^~~~~~~~~
49.60   ggml.c:1828:20: note: called from here
49.60    1828 |             x[i] = vaddq_f16(x[i], x[offset+i]);                  \
49.60         |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
49.60   ggml.c:1847:41: note: in expansion of macro ‘GGML_F16x8_REDUCE’
49.60    1847 |     #define GGML_F16_VEC_REDUCE         GGML_F16x8_REDUCE
49.60         |                                         ^~~~~~~~~~~~~~~~~
49.60   ggml.c:2346:5: note: in expansion of macro ‘GGML_F16_VEC_REDUCE’
49.60    2346 |     GGML_F16_VEC_REDUCE(sumf, sum);
49.60         |     ^~~~~~~~~~~~~~~~~~~
49.60   /usr/lib/gcc/aarch64-linux-gnu/12/include/arm_neon.h:28760:1: error: inlining failed in call to ‘always_inline’ ‘vaddq_f16’: target specific option mismatch
49.60   28760 | vaddq_f16 (float16x8_t __a, float16x8_t __b)
49.60         | ^~~~~~~~~
49.60   ggml.c:1832:20: note: called from here
49.60    1832 |             x[i] = vaddq_f16(x[i], x[offset+i]);                  \
49.60         |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
49.60   ggml.c:1847:41: note: in expansion of macro ‘GGML_F16x8_REDUCE’
49.60    1847 |     #define GGML_F16_VEC_REDUCE         GGML_F16x8_REDUCE
49.60         |                                         ^~~~~~~~~~~~~~~~~
49.60   ggml.c:2346:5: note: in expansion of macro ‘GGML_F16_VEC_REDUCE’
49.60    2346 |     GGML_F16_VEC_REDUCE(sumf, sum);
49.60         |     ^~~~~~~~~~~~~~~~~~~
49.60   make: *** [Makefile:285: ggml.o] Error 1
49.60   ninja: build stopped: subcommand failed.
49.60   Traceback (most recent call last):
49.60     File "/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
49.60       cmkr.make(make_args, install_target=cmake_install_target, env=env)
49.60     File "/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/skbuild/cmaker.py", line 697, in make
49.60       self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
49.60     File "/tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/skbuild/cmaker.py", line 742, in make_impl
49.60       raise SKBuildError(msg)
49.60   
49.60   An error occurred while building with CMake.
49.60     Command:
49.60       /tmp/tmpkx4o11sf/.venv/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
49.60     Install target:
49.60       install
49.60     Source directory:
49.60       /tmp/tmpw53zyla9/llama_cpp_python-0.1.74
49.60     Working directory:
49.60       /tmp/tmpw53zyla9/llama_cpp_python-0.1.74/_skbuild/linux-aarch64-3.10/cmake-build
49.60   Please check the install target is valid and see CMake's output for more information.
49.60   
49.60   
49.60 
49.60   at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
49.60       143│ 
49.60       144│                 error = ChefBuildError("\n\n".join(message_parts))
49.60       145│ 
49.61       146│             if error is not None:
49.61     → 147│                 raise error from None
49.61       148│ 
49.61       149│             return path
49.61       150│ 
49.61       151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
49.61 
49.61 Note: This error originates from the build backend, and is likely not a problem with poetry but with llama-cpp-python (0.1.74) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "llama-cpp-python (==0.1.74)"'.
49.61 
------
failed to solve: process "/bin/sh -c poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi" did not complete successfully: exit code: 1
```

**Comment by shannonlal** [comment]
@3eif I got the same error earlier today when trying to install it on a macbook.  I was working with someone else who had same box and was blocked as well.  I ended up installing it from source

**Comment by 3eif** [comment]
> 

What do you mean by "installing it from source"?

**Comment by 3eif** [comment]
I'm able to run langflow just fine using the `langflow` command but I'd like to contribute to the repository so I need to either use the docker or the make commands. Both of which are not working for me. Are there any prerequisite packages or libraries I should have installed?
