### ISSUE TITLE
Missing module named 'passlib' when using docker compose

### ISSUE THREAD

**Issue by Decikingship** [logspace-ai/langflow#819]
**Describe the bug**

When I run docker compose up, I encountered the following error, any idea how to solve this?
```
ubuntu@10-11-72-88:~/docker/langflow$ sudo docker compose pull
[+] Pulling 2/0
 ✔ backend Skipped - No image to be pulled                                                                                                                                                                                                  0.0s 
 ✔ frontend Skipped - No image to be pulled                                                                                                                                                                                                 0.0s 
ubuntu@10-11-72-88:~/docker/langflow$ sudo docker compose up
[+] Running 2/0
 ✔ Container langflow-frontend-1  Created                                                                                                                                                                                                   0.0s 
 ✔ Container langflow-backend-1   Created                                                                                                                                                                                                   0.0s 
Attaching to langflow-backend-1, langflow-frontend-1
langflow-backend-1   | INFO:     Will watch for changes in these directories: ['/app']
langflow-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
langflow-backend-1   | INFO:     Started reloader process [1] using WatchFiles
langflow-frontend-1  | 
langflow-frontend-1  | > langflow@0.1.2 dev:docker
langflow-frontend-1  | > vite --host 0.0.0.0
langflow-frontend-1  | 
langflow-frontend-1  | 
langflow-frontend-1  | 
langflow-frontend-1  |   VITE v4.3.9  ready in 1508 ms
langflow-frontend-1  | 
langflow-frontend-1  | 
langflow-frontend-1  |   ➜  Local:   http://localhost:3000/
langflow-frontend-1  |   ➜  Network: http://172.24.0.2:3000/
langflow-frontend-1  | Error: The following dependencies are imported but could not be resolved:
langflow-frontend-1  | 
langflow-frontend-1  |   @radix-ui/react-form (imported by /home/node/app/src/modals/UserManagementModal/index.tsx)
langflow-frontend-1  |   @radix-ui/react-select (imported by /home/node/app/src/components/ui/select.tsx)
langflow-frontend-1  | 
langflow-frontend-1  | Are they installed?
langflow-frontend-1  |     at file:///home/node/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
langflow-frontend-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
langflow-frontend-1  |     at async file:///home/node/app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
langflow-frontend-1  | 
langflow-backend-1   | Process SpawnProcess-1:
langflow-backend-1   | Traceback (most recent call last):
langflow-backend-1   |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
langflow-backend-1   |     self.run()
langflow-backend-1   |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
langflow-backend-1   |     self._target(*self._args, **self._kwargs)
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
langflow-backend-1   |     target(sockets=sockets)
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
langflow-backend-1   |     return asyncio.run(self.serve(sockets=sockets))
langflow-backend-1   |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
langflow-backend-1   |     return loop.run_until_complete(main)
langflow-backend-1   |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
langflow-backend-1   |     config.load()
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
langflow-backend-1   |     self.loaded_app = import_from_string(self.app)
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
langflow-backend-1   |     raise exc from None
langflow-backend-1   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
langflow-backend-1   |     module = importlib.import_module(module_str)
langflow-backend-1   |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
langflow-backend-1   |     return _bootstrap._gcd_import(name[level:], package, level)
langflow-backend-1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
langflow-backend-1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
langflow-backend-1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
langflow-backend-1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
langflow-backend-1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
langflow-backend-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
langflow-backend-1   |   File "/app/src/backend/langflow/main.py", line 9, in <module>
langflow-backend-1   |     from langflow.routers import login, users, health
langflow-backend-1   |   File "/app/src/backend/langflow/routers/login.py", line 8, in <module>
langflow-backend-1   |     from langflow.auth.auth import (
langflow-backend-1   |   File "/app/src/backend/langflow/auth/auth.py", line 5, in <module>
langflow-backend-1   |     from passlib.context import CryptContext
langflow-backend-1   | ModuleNotFoundError: No module named 'passlib'
```

**To Reproduce**
1. git clone the project
2. sudo docker compose up

**Additional context**
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)

**Comment by Decikingship** [comment]
Problem solved by:
1. shut down the contain by using `docker compose down`
2. cleaning up docker image cache by using `docker image prune -a -f`
3. reinstall this project by using `docker compose up`
