### ISSUE TITLE
make backend does not work with Python 3.9

### ISSUE THREAD

**Issue by dove-young** [logspace-ai/langflow#842]
**Describe the bug**

**Browser and Version**

**To Reproduce**

**Screenshots**

**Additional context**

when I `make backend` in Python 3.9, there is `TypeError` 
```
# make backend
make install_backend
make[1]: Entering directory '/root/jupyter/langflow'
poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: langflow (0.5.0a0)
make[1]: Leaving directory '/root/jupyter/langflow'
poetry run uvicorn --factory src.backend.langflow.main:create_app --port 7860 --reload --log-level debug
INFO:     Will watch for changes in these directories: ['/root/jupyter/langflow']
INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
INFO:     Started reloader process [1438281] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.cache/pypoetry/virtualenvs/langflow-PmbGgHqv-py3.9/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/.cache/pypoetry/virtualenvs/langflow-PmbGgHqv-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/root/.cache/pypoetry/virtualenvs/langflow-PmbGgHqv-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/root/.cache/pypoetry/virtualenvs/langflow-PmbGgHqv-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/.cache/pypoetry/virtualenvs/langflow-PmbGgHqv-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/jupyter/langflow/src/backend/langflow/main.py", line 8, in <module>
    from langflow.api import router
  File "/root/jupyter/langflow/src/backend/langflow/api/__init__.py", line 1, in <module>
    from langflow.api.router import router
  File "/root/jupyter/langflow/src/backend/langflow/api/router.py", line 3, in <module>
    from langflow.api.v1 import (
  File "/root/jupyter/langflow/src/backend/langflow/api/v1/__init__.py", line 2, in <module>
    from langflow.api.v1.validate import router as validate_router
  File "/root/jupyter/langflow/src/backend/langflow/api/v1/validate.py", line 3, in <module>
    from langflow.api.v1.base import (
  File "/root/jupyter/langflow/src/backend/langflow/api/v1/base.py", line 42, in <module>
    class PromptValidationResponse(BaseModel):
  File "/root/jupyter/langflow/src/backend/langflow/api/v1/base.py", line 45, in PromptValidationResponse
    frontend_node: FrontendNodeRequest | object
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'type'
```

And when I upgrade to Python 3.11, it claimed that Python (>=3.9,<3.11) is required. But actually it cannot work with Python 3.9
```
# make backend
make install_backend
make[1]: Entering directory '/root/jupyter/langflow'
poetry install
The currently activated Python version 3.11.2 is not supported by the project (>=3.9,<3.11).
Trying to find and use a compatible version.
```

**Comment by anovazzi1** [comment]
Have you ever tried python 3.10?

**Comment by niklaspm** [comment]
> Have you ever tried python 3.10?

`python = ">=3.9,<3.11"`

I checked and 3.9 isn't working (`poetry run langflow`) but 3.10.12 works just fine.
