### ISSUE TITLE
There is something wrong with this prompt, please review it

### ISSUE THREAD

**Issue by alanzchen** [logspace-ai/langflow#939]
**Describe the bug**
Deployed v0.4.20, while saving any prompt (even the simplest one like "hi") the following error message occurred: 
```
There is something wrong with this prompt, please review it
```

However, there is no other specific error.

**Browser and Version**
 - Arc (Chromium)
 - Chromium Engine Version 116.0.5845.187

**To Reproduce**
1. Edit any prompt
2. Click on "Check & Save"

**Additional context**
I suspect this is a frontend issue. I cannot replicate this on the official langflow huggingface space, but I see this error on my local machine and on my forked huggingface space.

I cannot launch with `--dev` as the following error is blocking the entire application:

```
[23:21:45] ERROR    [23:21:45] - ERROR - Vector Store AlibabaCloudOpenSearch not loaded: __name__                base.py:42
           ERROR    [23:21:45] - ERROR - Node AlibabaCloudOpenSearch not loaded                                  base.py:74
[2023-09-19 23:21:45 -0500] [22762] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/interface/vector_store/base.py", line 34, in get_signature
    return build_template_from_method(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/utils/util.py", line 141, in build_template_from_method
    raise ValueError(
ValueError: Method from_texts not found in class AlibabaCloudOpenSearchSettings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/api/v1/endpoints.py", line 39, in get_all
    native_components = build_langchain_types_dict()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/interface/types.py", line 80, in build_langchain_types_dict
    created_types = creator.to_dict()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/interface/base.py", line 64, in to_dict
    node = self.frontend_node(name)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/interface/base.py", line 72, in frontend_node
    signature = self.get_signature(name)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/langflow/interface/vector_store/base.py", line 40, in get_signature
    raise ValueError(f"Vector Store {name} not found") from exc
ValueError: Vector Store AlibabaCloudOpenSearchSettings not found
```

**Comment by anovazzi1** [comment]
which branch are you using?

**Comment by alanzchen** [comment]
Master. I just pip installed it with no version specified in the command.

**Comment by anovazzi1** [comment]
right, I think I know what it is, it's already fixed in the next release.

**Comment by aidanVEITA** [comment]
I'm having the same issue using the current version of Langflow locally.
